-- ACADRIX PYQ backend schema
-- Run this in Supabase SQL Editor after creating a project.

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  regulation text not null check (regulation in ('r2021','r2025')),
  semester smallint not null check (semester between 1 and 8),
  code text not null,
  name text not null,
  created_at timestamptz not null default now(),
  unique (regulation, semester, code)
);

create table if not exists public.pyqs (
  id bigint generated by default as identity primary key,
  regulation text not null check (regulation in ('r2021','r2025')),
  semester smallint not null check (semester between 1 and 8),
  subject_id bigint not null references public.subjects(id) on delete cascade,
  year smallint not null check (year between 2000 and 2100),
  session text not null,
  title text,
  storage_path text not null unique,
  original_filename text not null,
  file_size bigint,
  mime_type text not null default 'application/pdf' check (mime_type = 'application/pdf'),
  status text not null default 'published' check (status in ('draft','published','archived')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (regulation, semester, subject_id, year, session)
);

create index if not exists pyqs_subject_idx on public.pyqs(subject_id, year desc);
create index if not exists pyqs_filter_idx on public.pyqs(regulation, semester, year desc);

alter table public.subjects enable row level security;
alter table public.pyqs enable row level security;

create policy "public can read published subjects"
on public.subjects for select using (true);

create policy "public can read published pyqs"
on public.pyqs for select using (status = 'published');

-- Admin writes should be performed through an authenticated server-side function/API.
-- Do not grant anonymous insert/update/delete policies.

insert into storage.buckets (id, name, public)
values ('pyqs', 'pyqs', false)
on conflict (id) do nothing;

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists pyqs_touch_updated_at on public.pyqs;
create trigger pyqs_touch_updated_at
before update on public.pyqs
for each row execute function public.touch_updated_at();
